# Project: divideyvenceras
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Principa.o
LINKOBJ  = Principa.o
LIBS     = -L"C:/Users/tonat/OneDrive/Documents/tona otros trabajos/NetBeansProjects/Dev-Cpp/MinGW64/lib" -L"C:/Users/tonat/OneDrive/Documents/tona otros trabajos/NetBeansProjects/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -pg
INCS     = -I"C:/Users/tonat/OneDrive/Documents/tona otros trabajos/NetBeansProjects/Dev-Cpp/MinGW64/include" -I"C:/Users/tonat/OneDrive/Documents/tona otros trabajos/NetBeansProjects/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/tonat/OneDrive/Documents/tona otros trabajos/NetBeansProjects/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/tonat/OneDrive/Documents/tona otros trabajos/NetBeansProjects/Dev-Cpp/MinGW64/include" -I"C:/Users/tonat/OneDrive/Documents/tona otros trabajos/NetBeansProjects/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/tonat/OneDrive/Documents/tona otros trabajos/NetBeansProjects/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/tonat/OneDrive/Documents/tona otros trabajos/NetBeansProjects/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = divideyvenceras.exe
CXXFLAGS = $(CXXINCS) -pg
CFLAGS   = $(INCS) -pg
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Principa.o: Principa.cpp
	$(CPP) -c Principa.cpp -o Principa.o $(CXXFLAGS)
